/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pistas;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
/**
 *
 * @author Ivan
 */
public class PistasInterfaz extends javax.swing.JFrame {

    public PistasInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        FIFO = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PRealizadasFIFO = new javax.swing.JTextField();
        PSatisfacerFIFO = new javax.swing.JTextField();
        PSatisfechasFIFO = new javax.swing.JTextField();
        PRecorridasFIFO = new javax.swing.JTextField();
        PromedioRSFIFO = new javax.swing.JTextField();
        TiempoRecorriendoFIFO = new javax.swing.JTextField();
        TTransferenciaFIFO = new javax.swing.JTextField();
        TTotalFIFO = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPorSatisfacerFIFO = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaSatisfechasFIFO = new javax.swing.JList();
        SSTF = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        PRealizadasSSTF = new javax.swing.JTextField();
        PSatisfacerSSTF = new javax.swing.JTextField();
        PSatisfechasSSTF = new javax.swing.JTextField();
        PRecorridasSSTF = new javax.swing.JTextField();
        PromedioRSSSTF = new javax.swing.JTextField();
        TiempoRecorriendoSSTF = new javax.swing.JTextField();
        TTransferenciaSSTF = new javax.swing.JTextField();
        TTotalSSTF = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaPorSatisfacerSSTF = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListaSatisfechasSSTF = new javax.swing.JList();
        SCANL = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        PRealizadasSCANL = new javax.swing.JTextField();
        PSatisfacerSCANL = new javax.swing.JTextField();
        PSatisfechasSCANL = new javax.swing.JTextField();
        PRecorridasSCANL = new javax.swing.JTextField();
        PromedioRSSCANL = new javax.swing.JTextField();
        TiempoRecorriendoSCANL = new javax.swing.JTextField();
        TTransferenciaSCANL = new javax.swing.JTextField();
        TTotalSCANL = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListaPorSatisfacerSCANL = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        ListaSatisfechasSCANL = new javax.swing.JList();
        CSCAN = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        PRealizadasCSCAN = new javax.swing.JTextField();
        PSatisfacerCSCAN = new javax.swing.JTextField();
        PSatisfechasCSCAN = new javax.swing.JTextField();
        PRecorridasCSCAN = new javax.swing.JTextField();
        PromedioRSCSCAN = new javax.swing.JTextField();
        TiempoRecorriendoCSCAN = new javax.swing.JTextField();
        TTransferenciaCSCAN = new javax.swing.JTextField();
        TTotalCSCAN = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        ListaPorSatisfacerCSCAN = new javax.swing.JList();
        jScrollPane8 = new javax.swing.JScrollPane();
        ListaSatisfechasCSCAN = new javax.swing.JList();
        FSCAN = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        PRealizadasFSCAN = new javax.swing.JTextField();
        PSatisfacerFSCAN = new javax.swing.JTextField();
        PSatisfechasFSCAN = new javax.swing.JTextField();
        PRecorridasFSCAN = new javax.swing.JTextField();
        PromedioRSFSCAN = new javax.swing.JTextField();
        TiempoRecorriendoFSCAN = new javax.swing.JTextField();
        TTransferenciaFSCAN = new javax.swing.JTextField();
        TTotalFSCAN = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        ListaPorSatisfacerFSCAN = new javax.swing.JList();
        jScrollPane10 = new javax.swing.JScrollPane();
        ListaSatisfechasFSCAN = new javax.swing.JList();
        jScrollPane11 = new javax.swing.JScrollPane();
        ColaAFSCAN = new javax.swing.JList();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        ColaBFSCAN = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Iniciar = new javax.swing.JButton();
        Pausar = new javax.swing.JButton();
        Reanudar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Integrantes");

        jLabel58.setText("Juan Blanco");

        jLabel59.setText("Samuel Carmona");

        jLabel60.setText("Ivan Loscher");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel58)
                    .add(jLabel59)
                    .add(jLabel60))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel58)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel59)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel60)
                .addContainerGap())
        );

        tabs.setBackground(new java.awt.Color(204, 204, 204));

        FIFO.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Peticiones realizadas:");

        jLabel4.setText("Peticiones por satisfacer:");

        jLabel5.setText("Peticiones satisfechas:");

        jLabel9.setText("Pistas recorridas:");

        jLabel10.setText("Promedio de recorridas por peticion  satisfecha:");

        jLabel11.setText("Tiempo recorriendo pistas:");

        jLabel12.setText("Tiempo de transferencia entre peticiones:");

        jLabel13.setText("Tiempo total empleado:");

        jLabel7.setText("Por satisfacer:");

        jLabel6.setText("Listas:");

        jLabel8.setText("Satisfechas:");

        PRealizadasFIFO.setEditable(false);
        PRealizadasFIFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRealizadasFIFOActionPerformed(evt);
            }
        });

        PSatisfacerFIFO.setEditable(false);
        PSatisfacerFIFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSatisfacerFIFOActionPerformed(evt);
            }
        });

        PSatisfechasFIFO.setEditable(false);
        PSatisfechasFIFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSatisfechasFIFOActionPerformed(evt);
            }
        });

        PRecorridasFIFO.setEditable(false);
        PRecorridasFIFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRecorridasFIFOActionPerformed(evt);
            }
        });

        PromedioRSFIFO.setEditable(false);
        PromedioRSFIFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromedioRSFIFOActionPerformed(evt);
            }
        });

        TiempoRecorriendoFIFO.setEditable(false);

        TTransferenciaFIFO.setEditable(false);

        TTotalFIFO.setEditable(false);

        jScrollPane1.setViewportView(ListaPorSatisfacerFIFO);

        jScrollPane2.setViewportView(ListaSatisfechasFIFO);

        org.jdesktop.layout.GroupLayout FIFOLayout = new org.jdesktop.layout.GroupLayout(FIFO);
        FIFO.setLayout(FIFOLayout);
        FIFOLayout.setHorizontalGroup(
            FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(FIFOLayout.createSequentialGroup()
                .addContainerGap()
                .add(FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(FIFOLayout.createSequentialGroup()
                        .add(FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(FIFOLayout.createSequentialGroup()
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PSatisfacerFIFO, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                            .add(FIFOLayout.createSequentialGroup()
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PRealizadasFIFO)))
                        .add(FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(FIFOLayout.createSequentialGroup()
                                .add(28, 28, 28)
                                .add(jLabel6))
                            .add(FIFOLayout.createSequentialGroup()
                                .add(53, 53, 53)
                                .add(FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel7))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 44, Short.MAX_VALUE)
                                .add(FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel8)
                                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(139, 139, 139))
                    .add(FIFOLayout.createSequentialGroup()
                        .add(FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, TTransferenciaFIFO)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, PromedioRSFIFO)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, FIFOLayout.createSequentialGroup()
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PSatisfechasFIFO))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, FIFOLayout.createSequentialGroup()
                                .add(jLabel9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PRecorridasFIFO))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, FIFOLayout.createSequentialGroup()
                                .add(jLabel11)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(TiempoRecorriendoFIFO))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel12)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, FIFOLayout.createSequentialGroup()
                                .add(jLabel13)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(TTotalFIFO)))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        FIFOLayout.setVerticalGroup(
            FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, FIFOLayout.createSequentialGroup()
                .addContainerGap()
                .add(FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(PRealizadasFIFO, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel6)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel7)
                        .add(jLabel8))
                    .add(jLabel4)
                    .add(PSatisfacerFIFO, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(FIFOLayout.createSequentialGroup()
                        .add(FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel5)
                            .add(PSatisfechasFIFO, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9)
                            .add(PRecorridasFIFO, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel10)
                        .add(4, 4, 4)
                        .add(PromedioRSFIFO, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel11)
                            .add(TiempoRecorriendoFIFO, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel12)
                        .add(1, 1, 1)
                        .add(TTransferenciaFIFO, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(FIFOLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel13)
                            .add(TTotalFIFO, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jScrollPane1)
                    .add(jScrollPane2))
                .addContainerGap())
        );

        tabs.addTab("FIFO", FIFO);

        SSTF.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setText("Peticiones realizadas:");

        jLabel15.setText("Peticiones por satisfacer:");

        jLabel16.setText("Peticiones satisfechas:");

        jLabel17.setText("Pistas recorridas:");

        jLabel18.setText("Promedio de recorridas por peticion  satisfecha:");

        jLabel19.setText("Tiempo recorriendo pistas:");

        jLabel20.setText("Tiempo de transferencia entre peticiones:");

        jLabel21.setText("Tiempo total empleado:");

        jLabel22.setText("Por satisfacer:");

        jLabel23.setText("Listas:");

        jLabel24.setText("Satisfechas:");

        PRealizadasSSTF.setEditable(false);
        PRealizadasSSTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRealizadasSSTFActionPerformed(evt);
            }
        });

        PSatisfacerSSTF.setEditable(false);
        PSatisfacerSSTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSatisfacerSSTFActionPerformed(evt);
            }
        });

        PSatisfechasSSTF.setEditable(false);
        PSatisfechasSSTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSatisfechasSSTFActionPerformed(evt);
            }
        });

        PRecorridasSSTF.setEditable(false);
        PRecorridasSSTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRecorridasSSTFActionPerformed(evt);
            }
        });

        PromedioRSSSTF.setEditable(false);
        PromedioRSSSTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromedioRSSSTFActionPerformed(evt);
            }
        });

        TiempoRecorriendoSSTF.setEditable(false);

        TTransferenciaSSTF.setEditable(false);

        TTotalSSTF.setEditable(false);

        jScrollPane3.setViewportView(ListaPorSatisfacerSSTF);

        jScrollPane4.setViewportView(ListaSatisfechasSSTF);

        org.jdesktop.layout.GroupLayout SSTFLayout = new org.jdesktop.layout.GroupLayout(SSTF);
        SSTF.setLayout(SSTFLayout);
        SSTFLayout.setHorizontalGroup(
            SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(SSTFLayout.createSequentialGroup()
                .addContainerGap()
                .add(SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(SSTFLayout.createSequentialGroup()
                        .add(SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(SSTFLayout.createSequentialGroup()
                                .add(jLabel15)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PSatisfacerSSTF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                            .add(SSTFLayout.createSequentialGroup()
                                .add(jLabel14)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PRealizadasSSTF)))
                        .add(SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(SSTFLayout.createSequentialGroup()
                                .add(28, 28, 28)
                                .add(jLabel23))
                            .add(SSTFLayout.createSequentialGroup()
                                .add(53, 53, 53)
                                .add(SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel22))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 44, Short.MAX_VALUE)
                                .add(SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel24)
                                    .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(139, 139, 139))
                    .add(SSTFLayout.createSequentialGroup()
                        .add(SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, TTransferenciaSSTF)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, PromedioRSSSTF)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, SSTFLayout.createSequentialGroup()
                                .add(jLabel16)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PSatisfechasSSTF))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, SSTFLayout.createSequentialGroup()
                                .add(jLabel17)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PRecorridasSSTF))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel18, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, SSTFLayout.createSequentialGroup()
                                .add(jLabel19)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(TiempoRecorriendoSSTF))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel20)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, SSTFLayout.createSequentialGroup()
                                .add(jLabel21)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(TTotalSSTF)))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        SSTFLayout.setVerticalGroup(
            SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, SSTFLayout.createSequentialGroup()
                .addContainerGap()
                .add(SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel14)
                    .add(SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(PRealizadasSSTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel23)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel22)
                        .add(jLabel24))
                    .add(jLabel15)
                    .add(PSatisfacerSSTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(SSTFLayout.createSequentialGroup()
                        .add(SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel16)
                            .add(PSatisfechasSSTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel17)
                            .add(PRecorridasSSTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel18)
                        .add(4, 4, 4)
                        .add(PromedioRSSSTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel19)
                            .add(TiempoRecorriendoSSTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel20)
                        .add(1, 1, 1)
                        .add(TTransferenciaSSTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(SSTFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel21)
                            .add(TTotalSSTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jScrollPane3)
                    .add(jScrollPane4))
                .addContainerGap())
        );

        tabs.addTab("SSTF", SSTF);

        SCANL.setBackground(new java.awt.Color(204, 204, 204));

        jLabel25.setText("Peticiones realizadas:");

        jLabel26.setText("Peticiones por satisfacer:");

        jLabel27.setText("Peticiones satisfechas:");

        jLabel28.setText("Pistas recorridas:");

        jLabel29.setText("Promedio de recorridas por peticion  satisfecha:");

        jLabel30.setText("Tiempo recorriendo pistas:");

        jLabel31.setText("Tiempo de transferencia entre peticiones:");

        jLabel32.setText("Tiempo total empleado:");

        jLabel33.setText("Por satisfacer:");

        jLabel34.setText("Listas:");

        jLabel35.setText("Satisfechas:");

        PRealizadasSCANL.setEditable(false);
        PRealizadasSCANL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRealizadasSCANLActionPerformed(evt);
            }
        });

        PSatisfacerSCANL.setEditable(false);
        PSatisfacerSCANL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSatisfacerSCANLActionPerformed(evt);
            }
        });

        PSatisfechasSCANL.setEditable(false);
        PSatisfechasSCANL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSatisfechasSCANLActionPerformed(evt);
            }
        });

        PRecorridasSCANL.setEditable(false);
        PRecorridasSCANL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRecorridasSCANLActionPerformed(evt);
            }
        });

        PromedioRSSCANL.setEditable(false);
        PromedioRSSCANL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromedioRSSCANLActionPerformed(evt);
            }
        });

        TiempoRecorriendoSCANL.setEditable(false);

        TTransferenciaSCANL.setEditable(false);

        TTotalSCANL.setEditable(false);

        jScrollPane5.setViewportView(ListaPorSatisfacerSCANL);

        jScrollPane6.setViewportView(ListaSatisfechasSCANL);

        org.jdesktop.layout.GroupLayout SCANLLayout = new org.jdesktop.layout.GroupLayout(SCANL);
        SCANL.setLayout(SCANLLayout);
        SCANLLayout.setHorizontalGroup(
            SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(SCANLLayout.createSequentialGroup()
                .addContainerGap()
                .add(SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(SCANLLayout.createSequentialGroup()
                        .add(SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(SCANLLayout.createSequentialGroup()
                                .add(jLabel26)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PSatisfacerSCANL, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                            .add(SCANLLayout.createSequentialGroup()
                                .add(jLabel25)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PRealizadasSCANL)))
                        .add(SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(SCANLLayout.createSequentialGroup()
                                .add(28, 28, 28)
                                .add(jLabel34))
                            .add(SCANLLayout.createSequentialGroup()
                                .add(53, 53, 53)
                                .add(SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel33))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 44, Short.MAX_VALUE)
                                .add(SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel35)
                                    .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(139, 139, 139))
                    .add(SCANLLayout.createSequentialGroup()
                        .add(SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, TTransferenciaSCANL)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, PromedioRSSCANL)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, SCANLLayout.createSequentialGroup()
                                .add(jLabel27)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PSatisfechasSCANL))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, SCANLLayout.createSequentialGroup()
                                .add(jLabel28)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PRecorridasSCANL))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel29, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, SCANLLayout.createSequentialGroup()
                                .add(jLabel30)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(TiempoRecorriendoSCANL))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel31)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, SCANLLayout.createSequentialGroup()
                                .add(jLabel32)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(TTotalSCANL)))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        SCANLLayout.setVerticalGroup(
            SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, SCANLLayout.createSequentialGroup()
                .addContainerGap()
                .add(SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel25)
                    .add(SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(PRealizadasSCANL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel34)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel33)
                        .add(jLabel35))
                    .add(jLabel26)
                    .add(PSatisfacerSCANL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(SCANLLayout.createSequentialGroup()
                        .add(SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel27)
                            .add(PSatisfechasSCANL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel28)
                            .add(PRecorridasSCANL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel29)
                        .add(4, 4, 4)
                        .add(PromedioRSSCANL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel30)
                            .add(TiempoRecorriendoSCANL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel31)
                        .add(1, 1, 1)
                        .add(TTransferenciaSCANL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(SCANLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel32)
                            .add(TTotalSCANL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jScrollPane5)
                    .add(jScrollPane6))
                .addContainerGap())
        );

        tabs.addTab("SCANL", SCANL);

        CSCAN.setBackground(new java.awt.Color(204, 204, 204));

        jLabel36.setText("Peticiones realizadas:");

        jLabel37.setText("Peticiones por satisfacer:");

        jLabel38.setText("Peticiones satisfechas:");

        jLabel39.setText("Pistas recorridas:");

        jLabel40.setText("Promedio de recorridas por peticion  satisfecha:");

        jLabel41.setText("Tiempo recorriendo pistas:");

        jLabel42.setText("Tiempo de transferencia entre peticiones:");

        jLabel43.setText("Tiempo total empleado:");

        jLabel44.setText("Por satisfacer:");

        jLabel45.setText("Listas:");

        jLabel46.setText("Satisfechas:");

        PRealizadasCSCAN.setEditable(false);
        PRealizadasCSCAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRealizadasCSCANActionPerformed(evt);
            }
        });

        PSatisfacerCSCAN.setEditable(false);
        PSatisfacerCSCAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSatisfacerCSCANActionPerformed(evt);
            }
        });

        PSatisfechasCSCAN.setEditable(false);
        PSatisfechasCSCAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSatisfechasCSCANActionPerformed(evt);
            }
        });

        PRecorridasCSCAN.setEditable(false);
        PRecorridasCSCAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRecorridasCSCANActionPerformed(evt);
            }
        });

        PromedioRSCSCAN.setEditable(false);
        PromedioRSCSCAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromedioRSCSCANActionPerformed(evt);
            }
        });

        TiempoRecorriendoCSCAN.setEditable(false);

        TTransferenciaCSCAN.setEditable(false);

        TTotalCSCAN.setEditable(false);

        jScrollPane7.setViewportView(ListaPorSatisfacerCSCAN);

        jScrollPane8.setViewportView(ListaSatisfechasCSCAN);

        org.jdesktop.layout.GroupLayout CSCANLayout = new org.jdesktop.layout.GroupLayout(CSCAN);
        CSCAN.setLayout(CSCANLayout);
        CSCANLayout.setHorizontalGroup(
            CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(CSCANLayout.createSequentialGroup()
                .addContainerGap()
                .add(CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(CSCANLayout.createSequentialGroup()
                        .add(CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(CSCANLayout.createSequentialGroup()
                                .add(jLabel37)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PSatisfacerCSCAN, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                            .add(CSCANLayout.createSequentialGroup()
                                .add(jLabel36)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PRealizadasCSCAN)))
                        .add(CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(CSCANLayout.createSequentialGroup()
                                .add(28, 28, 28)
                                .add(jLabel45))
                            .add(CSCANLayout.createSequentialGroup()
                                .add(53, 53, 53)
                                .add(CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jScrollPane7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel44))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 44, Short.MAX_VALUE)
                                .add(CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel46)
                                    .add(jScrollPane8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(139, 139, 139))
                    .add(CSCANLayout.createSequentialGroup()
                        .add(CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, TTransferenciaCSCAN)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, PromedioRSCSCAN)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, CSCANLayout.createSequentialGroup()
                                .add(jLabel38)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PSatisfechasCSCAN))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, CSCANLayout.createSequentialGroup()
                                .add(jLabel39)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PRecorridasCSCAN))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel40, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, CSCANLayout.createSequentialGroup()
                                .add(jLabel41)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(TiempoRecorriendoCSCAN))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel42)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, CSCANLayout.createSequentialGroup()
                                .add(jLabel43)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(TTotalCSCAN)))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        CSCANLayout.setVerticalGroup(
            CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, CSCANLayout.createSequentialGroup()
                .addContainerGap()
                .add(CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel36)
                    .add(CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(PRealizadasCSCAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel45)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel44)
                        .add(jLabel46))
                    .add(jLabel37)
                    .add(PSatisfacerCSCAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(CSCANLayout.createSequentialGroup()
                        .add(CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel38)
                            .add(PSatisfechasCSCAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel39)
                            .add(PRecorridasCSCAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel40)
                        .add(4, 4, 4)
                        .add(PromedioRSCSCAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel41)
                            .add(TiempoRecorriendoCSCAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel42)
                        .add(1, 1, 1)
                        .add(TTransferenciaCSCAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(CSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel43)
                            .add(TTotalCSCAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jScrollPane7)
                    .add(jScrollPane8))
                .addContainerGap())
        );

        tabs.addTab("CSCAN", CSCAN);

        FSCAN.setBackground(new java.awt.Color(204, 204, 204));

        jLabel47.setText("Peticiones realizadas:");

        jLabel48.setText("Peticiones por satisfacer:");

        jLabel49.setText("Peticiones satisfechas:");

        jLabel50.setText("Pistas recorridas:");

        jLabel51.setText("Promedio de recorridas por peticion  satisfecha:");

        jLabel52.setText("Tiempo recorriendo pistas:");

        jLabel53.setText("Tiempo de transferencia entre peticiones:");

        jLabel54.setText("Tiempo total empleado:");

        jLabel55.setText("Por satisfacer:");

        jLabel56.setText("Listas:");

        jLabel57.setText("Satisfechas:");

        PRealizadasFSCAN.setEditable(false);
        PRealizadasFSCAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRealizadasFSCANActionPerformed(evt);
            }
        });

        PSatisfacerFSCAN.setEditable(false);
        PSatisfacerFSCAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSatisfacerFSCANActionPerformed(evt);
            }
        });

        PSatisfechasFSCAN.setEditable(false);
        PSatisfechasFSCAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSatisfechasFSCANActionPerformed(evt);
            }
        });

        PRecorridasFSCAN.setEditable(false);
        PRecorridasFSCAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRecorridasFSCANActionPerformed(evt);
            }
        });

        PromedioRSFSCAN.setEditable(false);
        PromedioRSFSCAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromedioRSFSCANActionPerformed(evt);
            }
        });

        TiempoRecorriendoFSCAN.setEditable(false);

        TTransferenciaFSCAN.setEditable(false);

        TTotalFSCAN.setEditable(false);

        jScrollPane9.setViewportView(ListaPorSatisfacerFSCAN);

        jScrollPane10.setViewportView(ListaSatisfechasFSCAN);

        jScrollPane11.setViewportView(ColaAFSCAN);

        jLabel61.setText("Cola A");

        jLabel62.setText("Cola B");

        jScrollPane12.setViewportView(ColaBFSCAN);

        org.jdesktop.layout.GroupLayout FSCANLayout = new org.jdesktop.layout.GroupLayout(FSCAN);
        FSCAN.setLayout(FSCANLayout);
        FSCANLayout.setHorizontalGroup(
            FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(FSCANLayout.createSequentialGroup()
                .addContainerGap()
                .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(FSCANLayout.createSequentialGroup()
                        .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, TTransferenciaFSCAN)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, PromedioRSFSCAN)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, FSCANLayout.createSequentialGroup()
                                .add(jLabel49)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PSatisfechasFSCAN))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, FSCANLayout.createSequentialGroup()
                                .add(jLabel50)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PRecorridasFSCAN))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel51, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, FSCANLayout.createSequentialGroup()
                                .add(jLabel52)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(TiempoRecorriendoFSCAN))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel53)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, FSCANLayout.createSequentialGroup()
                                .add(jLabel54)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(TTotalFSCAN)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jScrollPane11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(FSCANLayout.createSequentialGroup()
                        .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(FSCANLayout.createSequentialGroup()
                                .add(jLabel48)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PSatisfacerFSCAN, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                            .add(FSCANLayout.createSequentialGroup()
                                .add(jLabel47)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PRealizadasFSCAN)))
                        .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(FSCANLayout.createSequentialGroup()
                                .add(28, 28, 28)
                                .add(jLabel56))
                            .add(FSCANLayout.createSequentialGroup()
                                .add(53, 53, 53)
                                .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jScrollPane9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel55))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 48, Short.MAX_VALUE)
                                .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel57)
                                    .add(jScrollPane10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(FSCANLayout.createSequentialGroup()
                                .add(20, 20, 20)
                                .add(jLabel61))
                            .add(FSCANLayout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jLabel62))
                            .add(FSCANLayout.createSequentialGroup()
                                .add(25, 25, 25)
                                .add(jScrollPane12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .add(22, 22, 22))
        );
        FSCANLayout.setVerticalGroup(
            FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, FSCANLayout.createSequentialGroup()
                .addContainerGap()
                .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(FSCANLayout.createSequentialGroup()
                        .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel47)
                            .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(PRealizadasFSCAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jLabel56)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, FSCANLayout.createSequentialGroup()
                        .add(jLabel61)
                        .add(3, 3, 3)))
                .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(FSCANLayout.createSequentialGroup()
                        .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel55)
                                .add(jLabel57))
                            .add(jLabel48)
                            .add(PSatisfacerFSCAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(FSCANLayout.createSequentialGroup()
                                .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel49)
                                    .add(PSatisfechasFSCAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel50)
                                    .add(PRecorridasFSCAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel51)
                                .add(4, 4, 4)
                                .add(PromedioRSFSCAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel52)
                                    .add(TiempoRecorriendoFSCAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel53)
                                .add(1, 1, 1)
                                .add(TTransferenciaFSCAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(FSCANLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel54)
                                    .add(TTotalFSCAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(0, 0, Short.MAX_VALUE))
                            .add(jScrollPane9)
                            .add(jScrollPane10)))
                    .add(FSCANLayout.createSequentialGroup()
                        .add(jScrollPane11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel62)
                        .add(3, 3, 3)
                        .add(jScrollPane12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tabs.addTab("FSCAN", FSCAN);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Ingresar Peticion:");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        Iniciar.setText("Iniciar");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        Pausar.setText("Pausar");

        Reanudar.setText("Reanudar");

        Salir.setText("Salir");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabs)
            .add(layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(Iniciar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Pausar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Reanudar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Salir)
                        .add(11, 11, 11)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(tabs)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(Iniciar)
                            .add(Pausar)
                            .add(Reanudar)
                            .add(Salir)))))
        );

        tabs.getAccessibleContext().setAccessibleName("FIFO");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PromedioRSFIFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromedioRSFIFOActionPerformed

    }//GEN-LAST:event_PromedioRSFIFOActionPerformed

    private void PRecorridasFIFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRecorridasFIFOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRecorridasFIFOActionPerformed

    private void PSatisfechasFIFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSatisfechasFIFOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PSatisfechasFIFOActionPerformed

    private void PSatisfacerFIFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSatisfacerFIFOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PSatisfacerFIFOActionPerformed

    private void PSatisfacerSSTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSatisfacerSSTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PSatisfacerSSTFActionPerformed

    private void PSatisfechasSSTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSatisfechasSSTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PSatisfechasSSTFActionPerformed

    private void PRecorridasSSTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRecorridasSSTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRecorridasSSTFActionPerformed

    private void PromedioRSSSTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromedioRSSSTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PromedioRSSSTFActionPerformed

    private void PSatisfacerSCANLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSatisfacerSCANLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PSatisfacerSCANLActionPerformed

    private void PSatisfechasSCANLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSatisfechasSCANLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PSatisfechasSCANLActionPerformed

    private void PRecorridasSCANLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRecorridasSCANLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRecorridasSCANLActionPerformed

    private void PromedioRSSCANLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromedioRSSCANLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PromedioRSSCANLActionPerformed

    private void PSatisfacerCSCANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSatisfacerCSCANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PSatisfacerCSCANActionPerformed

    private void PSatisfechasCSCANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSatisfechasCSCANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PSatisfechasCSCANActionPerformed

    private void PRecorridasCSCANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRecorridasCSCANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRecorridasCSCANActionPerformed

    private void PromedioRSCSCANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromedioRSCSCANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PromedioRSCSCANActionPerformed

    private void PSatisfacerFSCANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSatisfacerFSCANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PSatisfacerFSCANActionPerformed

    private void PSatisfechasFSCANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSatisfechasFSCANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PSatisfechasFSCANActionPerformed

    private void PRecorridasFSCANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRecorridasFSCANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRecorridasFSCANActionPerformed

    private void PromedioRSFSCANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromedioRSFSCANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PromedioRSFSCANActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        
    }//GEN-LAST:event_IniciarActionPerformed

    private void PRealizadasFIFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRealizadasFIFOActionPerformed

    }//GEN-LAST:event_PRealizadasFIFOActionPerformed

    private void PRealizadasSSTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRealizadasSSTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRealizadasSSTFActionPerformed

    private void PRealizadasSCANLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRealizadasSCANLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRealizadasSCANLActionPerformed

    private void PRealizadasCSCANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRealizadasCSCANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRealizadasCSCANActionPerformed

    private void PRealizadasFSCANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRealizadasFSCANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRealizadasFSCANActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PistasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PistasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PistasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PistasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PistasInterfaz().setVisible(true);
            }
        });
    }

    public void setPRealizadasCSCAN(String PRealizadasCSCAN) {
        this.PRealizadasCSCAN.setText(PRealizadasCSCAN);
    }

    public void setPRealizadasFIFO(String PRealizadasFIFO) {
        this.PRealizadasFIFO.setText(PRealizadasFIFO);
    }

    public void setPRealizadasFSCAN(String PRealizadasFSCAN) {
        this.PRealizadasFSCAN.setText(PRealizadasFSCAN);
    }

    public void setPRealizadasSCANL(String PRealizadasSCANL) {
        this.PRealizadasSCANL.setText(PRealizadasSCANL);
    }

    public void setPRealizadasSSTF(String PRealizadasSSTF) {
        this.PRealizadasSSTF.setText(PRealizadasSSTF);
    }

    public void setPRecorridasCSCAN(String PRecorridasCSCAN) {
        this.PRecorridasCSCAN.setText(PRecorridasCSCAN);
    }

    public void setPRecorridasFIFO(String PRecorridasFIFO) {
        this.PRecorridasFIFO.setText(PRecorridasFIFO);
    }

    public void setPRecorridasFSCAN(String PRecorridasFSCAN) {
        this.PRecorridasFSCAN.setText(PRecorridasFSCAN);
    }

    public void setPRecorridasSCANL(String PRecorridasSCANL) {
        this.PRecorridasSCANL.setText(PRecorridasSCANL); ;
    }

    public void setPRecorridasSSTF(String PRecorridasSSTF) {
        this.PRecorridasSSTF.setText(PRecorridasSSTF);
    }

    public void setPSatisfacerCSCAN(String PSatisfacerCSCAN) {
        this.PSatisfacerCSCAN.setText(PSatisfacerCSCAN);
    }

    public void setPSatisfacerFIFO(String PSatisfacerFIFO) {
        this.PSatisfacerFIFO.setText(PSatisfacerFIFO);
    }

    public void setPSatisfacerFSCAN(String PSatisfacerFSCAN) {
        this.PSatisfacerFSCAN.setText(PSatisfacerFSCAN);
    }

    public void setPSatisfacerSCANL(String PSatisfacerSCANL) {
        this.PSatisfacerSCANL.setText(PSatisfacerSCANL);
    }

    public void setPSatisfacerSSTF(String PSatisfacerSSTF) {
        this.PSatisfacerSSTF.setText(PSatisfacerSSTF);
    }

    public void setPSatisfechasCSCAN(String PSatisfechasCSCAN) {
        this.PSatisfechasCSCAN.setText(PSatisfechasCSCAN);
    }

    public void setPSatisfechasFIFO(String PSatisfechasFIFO) {
        this.PSatisfechasFIFO.setText(PSatisfechasFIFO);
    }

    public void setPSatisfechasFSCAN(String PSatisfechasFSCAN) {
        this.PSatisfechasFSCAN.setText(PSatisfechasFSCAN);
    }

    public void setPSatisfechasSCANL(String PSatisfechasSCANL) {
        this.PSatisfechasSCANL.setText(PSatisfechasSCANL);
    }

    public void setPSatisfechasSSTF(String PSatisfechasSSTF) {
        this.PSatisfechasSSTF.setText(PSatisfechasSSTF);
    }

    public void setPausar(JButton Pausar) {
        this.Pausar = Pausar;
    }

    public void setPromedioRSCSCAN(String PromedioRSCSCAN) {
        this.PromedioRSCSCAN.setText(PromedioRSCSCAN);
    }

    public void setPromedioRSFIFO(String PromedioRSFIFO) {
        this.PromedioRSFIFO.setText(PromedioRSFIFO);
    }

    public void setPromedioRSFSCAN(String PromedioRSFSCAN) {
        this.PromedioRSFSCAN.setText(PromedioRSFSCAN);
    }

    public void setPromedioRSSCANL(String PromedioRSSCANL) {
        this.PromedioRSSCANL.setText(PromedioRSSCANL);
    }

    public void setPromedioRSSSTF(String PromedioRSSSTF) {
        this.PromedioRSSSTF.setText(PromedioRSSSTF);
    }

    public void setTTotalCSCAN(String TTotalCSCAN) {
        this.TTotalCSCAN.setText(TTotalCSCAN);
    }

    public void setTTotalFIFO(String TTotalFIFO) {
        this.TTotalFIFO.setText(TTotalFIFO);
    }

    public void setTTotalFSCAN(String TTotalFSCAN) {
        this.TTotalFSCAN.setText(TTotalFSCAN);
    }

    public void setTTotalSCANL(String TTotalSCANL) {
        this.TTotalSCANL.setText(TTotalSCANL);
    }

    public void setTTotalSSTF(String TTotalSSTF) {
        this.TTotalSSTF.setText(TTotalSSTF);
    }

    public void setTTransferenciaCSCAN(String TTransferenciaCSCAN) {
        this.TTransferenciaCSCAN.setText(TTransferenciaCSCAN);
    }

    public void setTTransferenciaFIFO(String TTransferenciaFIFO) {
        this.TTransferenciaFIFO.setText(TTransferenciaFIFO);
    }

    public void setTTransferenciaFSCAN(String TTransferenciaFSCAN) {
        this.TTransferenciaFSCAN.setText(TTransferenciaFSCAN);
    }

    public void setTTransferenciaSCANL(String TTransferenciaSCANL) {
        this.TTransferenciaSCANL.setText(TTransferenciaSCANL);
    }

    public void setTTransferenciaSSTF(String TTransferenciaSSTF) {
        this.TTransferenciaSSTF.setText(TTransferenciaSSTF);
    }

    public void setTiempoRecorriendoCSCAN(String TiempoRecorriendoCSCAN) {
        this.TiempoRecorriendoCSCAN.setText(TiempoRecorriendoCSCAN);
    }

    public void setTiempoRecorriendoFIFO(String TiempoRecorriendoFIFO) {
        this.TiempoRecorriendoFIFO.setText(TiempoRecorriendoFIFO);
    }

    public void setTiempoRecorriendoFSCAN(String TiempoRecorriendoFSCAN) {
        this.TiempoRecorriendoFSCAN.setText(TiempoRecorriendoFSCAN);
    }

    public void setTiempoRecorriendoSCANL(String TiempoRecorriendoSCANL) {
        this.TiempoRecorriendoSCANL.setText(TiempoRecorriendoSCANL);
    }

    public void setTiempoRecorriendoSSTF(String TiempoRecorriendoSSTF) {
        this.TiempoRecorriendoSSTF .setText(TiempoRecorriendoSSTF);
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CSCAN;
    private javax.swing.JList ColaAFSCAN;
    private javax.swing.JList ColaBFSCAN;
    private javax.swing.JPanel FIFO;
    private javax.swing.JPanel FSCAN;
    private javax.swing.JButton Iniciar;
    private javax.swing.JList ListaPorSatisfacerCSCAN;
    private javax.swing.JList ListaPorSatisfacerFIFO;
    private javax.swing.JList ListaPorSatisfacerFSCAN;
    private javax.swing.JList ListaPorSatisfacerSCANL;
    private javax.swing.JList ListaPorSatisfacerSSTF;
    private javax.swing.JList ListaSatisfechasCSCAN;
    private javax.swing.JList ListaSatisfechasFIFO;
    private javax.swing.JList ListaSatisfechasFSCAN;
    private javax.swing.JList ListaSatisfechasSCANL;
    private javax.swing.JList ListaSatisfechasSSTF;
    private javax.swing.JTextField PRealizadasCSCAN;
    private javax.swing.JTextField PRealizadasFIFO;
    private javax.swing.JTextField PRealizadasFSCAN;
    private javax.swing.JTextField PRealizadasSCANL;
    private javax.swing.JTextField PRealizadasSSTF;
    private javax.swing.JTextField PRecorridasCSCAN;
    private javax.swing.JTextField PRecorridasFIFO;
    private javax.swing.JTextField PRecorridasFSCAN;
    private javax.swing.JTextField PRecorridasSCANL;
    private javax.swing.JTextField PRecorridasSSTF;
    private javax.swing.JTextField PSatisfacerCSCAN;
    private javax.swing.JTextField PSatisfacerFIFO;
    private javax.swing.JTextField PSatisfacerFSCAN;
    private javax.swing.JTextField PSatisfacerSCANL;
    private javax.swing.JTextField PSatisfacerSSTF;
    private javax.swing.JTextField PSatisfechasCSCAN;
    private javax.swing.JTextField PSatisfechasFIFO;
    private javax.swing.JTextField PSatisfechasFSCAN;
    private javax.swing.JTextField PSatisfechasSCANL;
    private javax.swing.JTextField PSatisfechasSSTF;
    private javax.swing.JButton Pausar;
    private javax.swing.JTextField PromedioRSCSCAN;
    private javax.swing.JTextField PromedioRSFIFO;
    private javax.swing.JTextField PromedioRSFSCAN;
    private javax.swing.JTextField PromedioRSSCANL;
    private javax.swing.JTextField PromedioRSSSTF;
    private javax.swing.JButton Reanudar;
    private javax.swing.JPanel SCANL;
    private javax.swing.JPanel SSTF;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField TTotalCSCAN;
    private javax.swing.JTextField TTotalFIFO;
    private javax.swing.JTextField TTotalFSCAN;
    private javax.swing.JTextField TTotalSCANL;
    private javax.swing.JTextField TTotalSSTF;
    private javax.swing.JTextField TTransferenciaCSCAN;
    private javax.swing.JTextField TTransferenciaFIFO;
    private javax.swing.JTextField TTransferenciaFSCAN;
    private javax.swing.JTextField TTransferenciaSCANL;
    private javax.swing.JTextField TTransferenciaSSTF;
    private javax.swing.JTextField TiempoRecorriendoCSCAN;
    private javax.swing.JTextField TiempoRecorriendoFIFO;
    private javax.swing.JTextField TiempoRecorriendoFSCAN;
    private javax.swing.JTextField TiempoRecorriendoSCANL;
    private javax.swing.JTextField TiempoRecorriendoSSTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
